### ISSUE TITLE
java.sql.SQLException: [Amazon](500310) Invalid operation: value too long for type character varying(17)

### ISSUE THREAD

**Issue by siannuzzi** [OHDSI/Legend#2]
Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: value too long for type character varying(17);

SQL:
INSERT INTO legend_study.legend_feasability_depression_attition (
	exposure_id,
	target_id,
	comparator_id,
	sequence_number,
	description,
	subjects)
SELECT exposure_id,
	target_id,
	comparator_id,
	sequence_number,
	description,
	subjects
FROM (
	-- Restricted to common period: take final number
	SELECT epcs.cohort_definition_id AS exposure_id,
		epcs.target_id,
		epcs.comparator_id,
		CAST(4 AS INT) AS sequence_number,
		CAST('Restricted to common period' AS VARCHAR(255)) AS description,
		epcs.num_persons AS subjects
	FROM #ep_cohort_summary epcs	
) temp

**Comment by schuemie** [comment]
Looks like the CREATE TABLE AS SELECT on Amazon didn't create the field types I was expecting. I've [switched to explicitly creating the table structure instead](https://github.com/OHDSI/Legend/commit/b7ab8391d81816e30295e9f9590feb32a58d28ef).

Can you reinstall the Legend package and try again?
